using System;
using System.Runtime.InteropServices;
using TilingWindowManager.Native;
using static TilingWindowManager.Native.NativeMethods;

namespace TilingWindowManager.Core;

/// <summary>
/// Listens to low-level Windows Accessibility Events (WinEvents) to detect when windows
/// are created, destroyed, moved, or focused.
/// It acts as the "eyes and ears" of the WindowManager.
/// </summary>
public class EventHookManager : IDisposable
{
    private IntPtr _hookCreate;
    private IntPtr _hookShowHide;
    private IntPtr _hookLocationChange;

    private System.Threading.Thread? _hookThread;
    private System.Windows.Threading.Dispatcher? _hookDispatcher;
    private int _wpfThreadId;

    // Keep reference to delegate so it is not garbage collected by the CLR
    private readonly WinEventDelegate _winEventDelegate;

    public event Action? WindowStateChanged;
    public event Action<IntPtr>? WindowMoveSizeStart;
    public event Action<IntPtr>? WindowMoveSizeEnd;
    public event Action<IntPtr>? WindowLocationChanged;

    public EventHookManager()
    {
        _winEventDelegate = WinEventCallback;
    }

    public void Start()
    {
        _wpfThreadId = NativeMethods.GetCurrentThreadId(); // Cache the WPF UI Thread ID to safely ignore our own operations
        
        _hookThread = new System.Threading.Thread(() =>
        {
            _hookDispatcher = System.Windows.Threading.Dispatcher.CurrentDispatcher;

            // 1. Setup WinEvent Hooks
            // PERFORMANCE: Instead of creating 6 separate hooks, we use event ID ranges.
            // This saves OS handles and prevents duplicate callbacks.
            // Combine Object Events: CREATE (0x8000) to HIDE (0x8003)
            _hookCreate = SetWinEventHook(
                EVENT_OBJECT_CREATE,
                EVENT_OBJECT_HIDE,
                IntPtr.Zero,
                _winEventDelegate,
                0,
                0,
                WINEVENT_OUTOFCONTEXT | WINEVENT_SKIPOWNPROCESS
            );

            // Combine System Events: FOREGROUND (0x0003) to MINIMIZEEND (0x0017)
            // This covers FOREGROUND, MOVESIZESTART/END, MINIMIZESTART/END
            _hookShowHide = SetWinEventHook(
                EVENT_SYSTEM_FOREGROUND,
                EVENT_SYSTEM_MINIMIZEEND,
                IntPtr.Zero,
                _winEventDelegate,
                0,
                0,
                WINEVENT_OUTOFCONTEXT | WINEVENT_SKIPOWNPROCESS
            );

            // Start an isolated message pump just for these hooks!
            System.Windows.Threading.Dispatcher.Run();
        })
        {
            IsBackground = true,
            Name = "WinEventHookThread"
        };
        _hookThread.SetApartmentState(System.Threading.ApartmentState.STA);
        _hookThread.Start();
    }

    private void WinEventCallback(
        IntPtr hWinEventHook,
        uint eventType,
        IntPtr hwnd,
        int idObject,
        int idChild,
        uint dwEventThread,
        uint dwmsEventTime
    )
    {
        if (idObject != OBJID_WINDOW)
            return;

        // CRITICAL FILTER: Ignore events for child elements (like scrollbars, menus, etc.)
        // idChild == 0 (CHILDID_SELF) means the event was fired for the window itself.
        if (idChild != 0)
            return;

        if (hwnd == IntPtr.Zero)
            return;

        // Ignore events generated by our own process (e.g. the HighlightOverlay repositioning)
        // This accurately ignores BOTH the background hook thread and the WPF layout engine thread.
        int currentThreadId = NativeMethods.GetCurrentThreadId();
        if (dwEventThread == currentThreadId || dwEventThread == _wpfThreadId)
            return;

        // CRITICAL FILTER: ONLY care about Top-Level Windows.
        // If we don't do this, the OS will send us an event for EVERY single UI element 
        // created inside an app (every button, tooltip, scrollbar, etc.), causing a massive "Event Storm".
        // GetAncestor(hwnd, GA_ROOT) checks if the window is the absolute top of the tree.
        if (NativeMethods.GetAncestor(hwnd, NativeMethods.GA_ROOT) != hwnd)
            return;

        if (eventType == EVENT_SYSTEM_MOVESIZESTART)
        {
            PlugInLocationHook();
            System.Windows.Application.Current.Dispatcher.InvokeAsync(() => WindowMoveSizeStart?.Invoke(hwnd));
        }
        else if (eventType == EVENT_SYSTEM_MOVESIZEEND)
        {
            UnplugLocationHook();
            System.Windows.Application.Current.Dispatcher.InvokeAsync(() => WindowMoveSizeEnd?.Invoke(hwnd));
        }
        else if (eventType == EVENT_OBJECT_LOCATIONCHANGE)
        {
            System.Windows.Application.Current.Dispatcher.InvokeAsync(() => WindowLocationChanged?.Invoke(hwnd));
        }

        if (
            eventType == EVENT_OBJECT_CREATE
            || eventType == EVENT_OBJECT_DESTROY
            || eventType == EVENT_OBJECT_SHOW
            || eventType == EVENT_OBJECT_HIDE
            || eventType == EVENT_SYSTEM_MINIMIZESTART
            || eventType == EVENT_SYSTEM_MINIMIZEEND
            || eventType == EVENT_SYSTEM_FOREGROUND
            || eventType == EVENT_SYSTEM_MOVESIZEEND
        )
        {
            TriggerEvent();
        }
    }

    private int _isRetileQueued = 0;

    /// <summary>
    /// Debounces multiple rapid events into a single layout pass.
    /// Example: Opening an app fires CREATE, SHOW, and FOREGROUND almost instantly.
    /// We queue a single retile operation to run on the next WPF Render frame to avoid doing the math 3 times.
    /// </summary>
    private void TriggerEvent()
    {
        // Thread-safe debounce check
        if (System.Threading.Interlocked.CompareExchange(ref _isRetileQueued, 1, 0) != 0) 
            return;

        System.Windows.Application.Current.Dispatcher.InvokeAsync(() =>
        {
            System.Threading.Interlocked.Exchange(ref _isRetileQueued, 0);
            WindowStateChanged?.Invoke();
        }, System.Windows.Threading.DispatcherPriority.Render);
    }

    private void PlugInLocationHook()
    {
        if (_hookLocationChange == IntPtr.Zero)
        {
            // Location Change Event covers real-time dragging and resizing (0x800B)
            _hookLocationChange = SetWinEventHook(
                EVENT_OBJECT_LOCATIONCHANGE,
                EVENT_OBJECT_LOCATIONCHANGE,
                IntPtr.Zero,
                _winEventDelegate,
                0,
                0,
                WINEVENT_OUTOFCONTEXT | WINEVENT_SKIPOWNPROCESS
            );
        }
    }

    private void UnplugLocationHook()
    {
        if (_hookLocationChange != IntPtr.Zero)
        {
            UnhookWinEvent(_hookLocationChange);
            _hookLocationChange = IntPtr.Zero;
        }
    }

    public void Dispose()
    {
        if (_hookDispatcher != null)
        {
            _hookDispatcher.Invoke(() =>
            {
                if (_hookCreate != IntPtr.Zero)
                    UnhookWinEvent(_hookCreate);
                if (_hookShowHide != IntPtr.Zero)
                    UnhookWinEvent(_hookShowHide);
                if (_hookLocationChange != IntPtr.Zero)
                    UnhookWinEvent(_hookLocationChange);

                _hookDispatcher.InvokeShutdown();
            });
            _hookThread?.Join(1000); // Wait gracefully for the background dispatcher to die
        }
    }
}
